### ISSUE TITLE
detect.policy.check.fail.on.severities is overridden in hub_load/submit_scans.sh

### ISSUE THREAD

**Issue by ghost** [blackducksoftware/hub-load#6]
`DETECT_OPTIONS="${DETECT_OPTIONS} --detect.policy.check.fail.on.severities=ALL"
`
overrides detect.policy.check.fail.on.severities that is set elsewhere. 
Can that be made configurable?
https://github.com/blackducksoftware/hub-load/blob/63efac5c89c477e0cb0c612ee091645cd45d4d82/src/hub_load/submit_scans.sh#L185
63efac5c89c477e0cb0c612ee091645cd45d4d82

**Comment by nichollsdave** [comment]
Hi @pjsnps 
This parameter is passed in to specify the test should be synchronous.  I propose changing this parameter to --detect.wait.for.results=true in this scenario to remove the hard coding of a particular level of policy check.  
In addition to this I can add an optional parameter for the value of detect.policy.check.fail.on.severities - if you pass in MAJOR it would set this parameter in submit_scans.sh.  

Does that work?  Essentially decoupling this parameter from the synchronous part and making the policy check severity another optional flag.

**Comment by nichollsdave** [comment]
Added variable FAIL_ON_SEVERITIES that by default is not set and does not get passed in.
Specifying a value to this e.g. MAJOR or ALL will result in a synchronous scan.  Another way to get a synchronous scan is to set SYNCHRONOUS_SCANS=true and this will pass in the parameter to tell Detect to wait for the results and will no longer do a policy check.  

Updated image at gsasig/hub-load:latest with this change
